package com.example.ui.localization

object GameStrings {
    private val strings = mapOf(
        "en" to mapOf(
            "app_title" to "Color Connect",
            "play" to "Play Game",
            "select_level" to "Level Select",
            "settings" to "Settings",
            "sound" to "Sound Effects",
            "music" to "Background Music",
            "vibration" to "Vibration",
            "language" to "Language",
            "reset_progress" to "Reset Game Progress",
            "reset_confirm_title" to "Reset Progress?",
            "reset_confirm_msg" to "All completed levels, stars, and coins will be reset. This cannot be undone.",
            "reset" to "Reset",
            "cancel" to "Cancel",
            "back" to "Back",
            "level" to "Level",
            "moves" to "Moves",
            "flow" to "Flow",
            "pipe" to "Pipe",
            "hints" to "Hints",
            "undo" to "Undo",
            "restart" to "Restart",
            "level_complete" to "LEVEL COMPLETE!",
            "perfect" to "PERFECT RUN!",
            "all_connected" to "All dots connected & board filled!",
            "next_level" to "Next Level",
            "retry" to "Retry",
            "home" to "Home",
            "coins_earned" to "+%d Coins",
            "need_hints" to "No hints left! Buy for 25 coins?",
            "buy" to "Buy Hint",
            "beginner_pack" to "5x5 Beginner",
            "easy_pack" to "6x6 Easy",
            "medium_pack" to "7x7 Medium",
            "hard_pack" to "8x8 Master",
            "stats" to "Progress",
            "stars" to "Stars",
            "locked" to "Locked",
            "night_mode" to "Night Mode",
            "light_mode" to "Light Mode",
            "theme" to "Theme",
            "watch_ad" to "Watch Ad",
            "watch_ad_reward" to "Watch Ad: Free Hint & Coins",
            "ad_badge" to "Ad",
            "sponsored_tip" to "Sponsored Puzzle Tip",
            "reward_ready" to "Reward Ready!",
            "reward_countdown" to "Reward in %ds",
            "claim_reward" to "Claim Reward (+1 Hint, +25 Coins)",
            "reward_earned_msg" to "+1 Free Hint & +25 Coins!",
            "next_tip" to "Next Tip",
            "puzzle_academy" to "Mastery Tips",
            "free_hint" to "Free Hint (Ad)"
        ),
        "es" to mapOf(
            "app_title" to "Color Connect",
            "play" to "Jugar",
            "select_level" to "Niveles",
            "settings" to "Ajustes",
            "sound" to "Efectos de Sonido",
            "music" to "Música de Fondo",
            "vibration" to "Vibración",
            "language" to "Idioma",
            "reset_progress" to "Restablecer Progreso",
            "reset_confirm_title" to "¿Restablecer Progreso?",
            "reset_confirm_msg" to "Se restablecerán todos los niveles completados, estrellas y monedas.",
            "reset" to "Restablecer",
            "cancel" to "Cancelar",
            "back" to "Atrás",
            "level" to "Nivel",
            "moves" to "Movimientos",
            "flow" to "Flujo",
            "pipe" to "Tubos",
            "hints" to "Pistas",
            "undo" to "Deshacer",
            "restart" to "Reiniciar",
            "level_complete" to "¡NIVEL COMPLETADO!",
            "perfect" to "¡PERFECTO!",
            "all_connected" to "¡Todos los puntos conectados!",
            "next_level" to "Siguiente Nivel",
            "retry" to "Reintentar",
            "home" to "Inicio",
            "coins_earned" to "+%d Monedas",
            "need_hints" to "¿Sin pistas? ¿Comprar por 25 monedas?",
            "buy" to "Comprar Pista",
            "beginner_pack" to "5x5 Principiante",
            "easy_pack" to "6x6 Fácil",
            "medium_pack" to "7x7 Medio",
            "hard_pack" to "8x8 Maestro",
            "stats" to "Progreso",
            "stars" to "Estrellas",
            "locked" to "Bloqueado",
            "night_mode" to "Modo Noche",
            "light_mode" to "Modo Claro",
            "theme" to "Tema",
            "watch_ad" to "Ver Anuncio",
            "watch_ad_reward" to "Ver Anuncio: Pista y Monedas",
            "ad_badge" to "Anuncio",
            "sponsored_tip" to "Consejo Pro Patrocinado",
            "reward_ready" to "¡Recompensa Lista!",
            "reward_countdown" to "Recompensa en %ds",
            "claim_reward" to "Reclamar (+1 Pista, +25 Monedas)",
            "reward_earned_msg" to "¡+1 Pista y +25 Monedas!",
            "next_tip" to "Siguiente Consejo",
            "puzzle_academy" to "Consejos Maestros",
            "free_hint" to "Pista Gratis (Anuncio)"
        ),
        "fr" to mapOf(
            "app_title" to "Color Connect",
            "play" to "Jouer",
            "select_level" to "Niveaux",
            "settings" to "Paramètres",
            "sound" to "Effets Sonores",
            "music" to "Musique",
            "vibration" to "Vibrations",
            "language" to "Langue",
            "reset_progress" to "Réinitialiser le Jeu",
            "reset_confirm_title" to "Réinitialiser?",
            "reset_confirm_msg" to "Toute la progression sera effacée.",
            "reset" to "Réinitialiser",
            "cancel" to "Annuler",
            "back" to "Retour",
            "level" to "Niveau",
            "moves" to "Coups",
            "flow" to "Flux",
            "pipe" to "Tuyau",
            "hints" to "Indices",
            "undo" to "Annuler",
            "restart" to "Recommencer",
            "level_complete" to "NIVEAU TERMINÉ!",
            "perfect" to "PARFAIT!",
            "all_connected" to "Tous les points sont connectés!",
            "next_level" to "Niveau Suivant",
            "retry" to "Rejouer",
            "home" to "Accueil",
            "coins_earned" to "+%d Pièces",
            "need_hints" to "Acheter un indice pour 25 pièces?",
            "buy" to "Acheter",
            "beginner_pack" to "5x5 Débutant",
            "easy_pack" to "6x6 Facile",
            "medium_pack" to "7x7 Moyen",
            "hard_pack" to "8x8 Maître",
            "stats" to "Progrès",
            "stars" to "Étoiles",
            "locked" to "Verrouillé",
            "night_mode" to "Mode Nuit",
            "light_mode" to "Mode Jour",
            "theme" to "Thème",
            "watch_ad" to "Regarder Pub",
            "watch_ad_reward" to "Regarder Pub: Indice et Pièces",
            "ad_badge" to "Pub",
            "sponsored_tip" to "Astuce Pro Sponsorisée",
            "reward_ready" to "Récompense Prête!",
            "reward_countdown" to "Récompense dans %ds",
            "claim_reward" to "Réclamer (+1 Indice, +25 Pièces)",
            "reward_earned_msg" to "+1 Indice et +25 Pièces!",
            "next_tip" to "Astuce Suivante",
            "puzzle_academy" to "Astuces de Maître",
            "free_hint" to "Indice Gratuit (Pub)"
        ),
        "de" to mapOf(
            "app_title" to "Color Connect",
            "play" to "Spielen",
            "select_level" to "Levelauswahl",
            "settings" to "Einstellungen",
            "sound" to "Toneffekte",
            "music" to "Musik",
            "vibration" to "Vibration",
            "language" to "Sprache",
            "reset_progress" to "Fortschritt zurücksetzen",
            "reset_confirm_title" to "Zurücksetzen?",
            "reset_confirm_msg" to "Der gesamte Spielfortschritt wird gelöscht.",
            "reset" to "Zurücksetzen",
            "cancel" to "Abbrechen",
            "back" to "Zurück",
            "level" to "Level",
            "moves" to "Züge",
            "flow" to "Fluss",
            "pipe" to "Rohre",
            "hints" to "Hinweise",
            "undo" to "Rückgängig",
            "restart" to "Neu starten",
            "level_complete" to "LEVEL GESCHAFFT!",
            "perfect" to "PERFEKT!",
            "all_connected" to "Alle Farben verbunden!",
            "next_level" to "Nächstes Level",
            "retry" to "Wiederholen",
            "home" to "Start",
            "coins_earned" to "+%d Münzen",
            "need_hints" to "Hinweis für 25 Münzen kaufen?",
            "buy" to "Kaufen",
            "beginner_pack" to "5x5 Anfänger",
            "easy_pack" to "6x6 Einfach",
            "medium_pack" to "7x7 Mittel",
            "hard_pack" to "8x8 Meister",
            "stats" to "Fortschritt",
            "stars" to "Sterne",
            "locked" to "Gesperrt",
            "night_mode" to "Nachtmodus",
            "light_mode" to "Hellmodus",
            "theme" to "Design",
            "watch_ad" to "Werbung ansehen",
            "watch_ad_reward" to "Werbung für Hinweis & Münzen",
            "ad_badge" to "Anzeige",
            "sponsored_tip" to "Gesponserter Pro-Tipp",
            "reward_ready" to "Belohnung bereit!",
            "reward_countdown" to "Belohnung in %ds",
            "claim_reward" to "Belohnung einfordern (+1 Hinweis, +25 Münzen)",
            "reward_earned_msg" to "+1 Hinweis & +25 Münzen!",
            "next_tip" to "Nächster Tipp",
            "puzzle_academy" to "Meister-Tipps",
            "free_hint" to "Kostenloser Hinweis (Ad)"
        ),
        "ja" to mapOf(
            "app_title" to "Color Connect",
            "play" to "プレイ",
            "select_level" to "ステージ選択",
            "settings" to "設定",
            "sound" to "効果音",
            "music" to "BGM",
            "vibration" to "バイブレーション",
            "language" to "言語",
            "reset_progress" to "進行状況をリセット",
            "reset_confirm_title" to "リセットしますか？",
            "reset_confirm_msg" to "クリアしたステージや獲得した星がすべて初期化されます。",
            "reset" to "リセット",
            "cancel" to "キャンセル",
            "back" to "戻る",
            "level" to "ステージ",
            "moves" to "手数",
            "flow" to "接続率",
            "pipe" to "ライン",
            "hints" to "ヒント",
            "undo" to "戻す",
            "restart" to "やり直し",
            "level_complete" to "ステージクリア！",
            "perfect" to "パーフェクト！",
            "all_connected" to "すべてのドットが繋がりました！",
            "next_level" to "次のステージ",
            "retry" to "もう一度",
            "home" to "ホーム",
            "coins_earned" to "+%d コイン",
            "need_hints" to "ヒントがありません。25コインで購入しますか？",
            "buy" to "購入",
            "beginner_pack" to "5x5 初級",
            "easy_pack" to "6x6 中級",
            "medium_pack" to "7x7 上級",
            "hard_pack" to "8x8 マスター",
            "stats" to "進行度",
            "stars" to "スター",
            "locked" to "未開放",
            "night_mode" to "ナイトモード",
            "light_mode" to "ライトモード",
            "theme" to "テーマ",
            "watch_ad" to "動画を見る",
            "watch_ad_reward" to "広告を見てヒントとコインを獲得",
            "ad_badge" to "広告",
            "sponsored_tip" to "スポンサー付きプロのヒント",
            "reward_ready" to "報酬を獲得できます！",
            "reward_countdown" to "あと%d秒で獲得",
            "claim_reward" to "報酬を受け取る（ヒント+1、コイン+25）",
            "reward_earned_msg" to "ヒント+1 & コイン+25 獲得！",
            "next_tip" to "次のヒント",
            "puzzle_academy" to "プロの攻略法",
            "free_hint" to "無料ヒント（広告）"
        )
    )

    fun get(key: String, lang: String): String {
        return strings[lang]?.get(key) ?: strings["en"]?.get(key) ?: key
    }

    val availableLanguages = listOf(
        "en" to "English",
        "es" to "Español",
        "fr" to "Français",
        "de" to "Deutsch",
        "ja" to "日本語"
    )
}
